#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5
#define SNAKE_COLLISION_BITMASK 0x000001
#define FOOD_COLLISION_BITMASK 0x000002
#define WALL_COLLISION_BITMASK 0x000003
#endif // __DEFINITIONS_H__
